---
title: "unit2-module1"
author: "Tanner Honnef"
date: "2024-03-18"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{module 4}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(sf)
# Read in the farmers_spatial.csv, districts.geojson, and roads.geojson 
# datasets. 

#Reduce the size of the farmers data by first selecting distinct observations 
#by uuid, x, y, season, i.e. use distinct(uuid, x, y, season). 

# After that convert it to an sf object.

# Reproject the farmers and districts data to Albers projection 
# (using the CRS from roads), naming each farmers_alb and districts_alb. 

# Ideally (worth an extra 0.5 points) you will do all the necessary steps to 
# create farmers_alb and districts_alb in one pipeline.

fnmR <- system.file("extdata/roads.geojson", package = "geospaar")
fnmR

roads <- st_read(dsn = fnmR)
roads

fnm <- system.file("extdata/districts.geojson", package = "geospaar")
districts <- st_read(dsn = fnm)
districts

districts_alb <- st_transform(districts, crs = st_crs(roads))
districts_alb

farmers_alb <- read_csv(
  system.file("extdata/farmer_spatial.csv", package = "geospaar")) %>%
  distinct(uuid, x, y, season) %>%
  st_as_sf(coords = c("x", "y")) %>%
  st_set_crs("EPSG:4326") %>%  
  st_transform(crs = st_crs(roads))
farmers_alb

```

```{r, fig.width=6, fig.height=4, fig.align='center'}
# Create a plot using sf::plot that shows all three datasets on one map, with
# districts_alb in grey, with roads in red over that, and farmers_alb as a blue
# cross over that. 

# Use the relevant chunk arguments to center the figure in the vignette html, 
# and to have a height of 4 inches and a width of 6 inches. 

# The figure should have 0 margins all around.

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(roads %>% st_geometry(), col = "red", add = TRUE)
plot(farmers_alb %>% st_geometry(), col = "blue", pch = "+", add = TRUE)
```

```{r, fig.width=5, fig.height=6, fig.align='center'}
# Make the same plot above using ggplot and geom_sf. 

# When adding farmers_alb to the plot, use pch = "+" and size = 3 as arguments 
# to geom_sf. Add the function theme_bw() to the ggplot construction chain, 
# to get rid of the grey background. 

# Make the “fill” (rather than “color”) of districts_alb grey. 

# Center the figure using chunk options and make the figure width 5 inches 
# and height 6 inches.

ggplot(districts_alb, fill = "grey") + geom_sf() + 
  geom_sf(data = roads, col = "red") + 
  geom_sf(data = farmers_alb, col = "blue", pch = "+", size = 3) +
  theme_bw()
```


```{r, fig.width=6, fig.height=4, fig.align='center'}
# Select from districts_alb the district representing the 50th percentile area, 
# i.e. the median area, and save that district into a new object median_dist. 

# Plot it in “khaki” on top of grey districts_alb. 

# Give the plot a title “The median area district”. 

# Same plot dimensions in the vignette html as for Task 2, but a leave a space
# of 1 at the top in the plot mar.

districts_alb <- districts_alb %>% 
  mutate(area = as.numeric(units::set_units(st_area(.), "km^2")))
districts_alb

medianArea <- quantile(districts_alb$area, 0.5, type = 1)
medianArea

median_dist <- districts_alb %>%
  filter(.$area == medianArea)
median_dist

par(mar = c(0, 0, 1, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(median_dist %>% st_geometry(), col = "khaki", add = TRUE)
title("The median area district")
```

```{r, fig.width=6, fig.height=4, fig.align='center'}
# Convert the median_dist to its centroid point. Call it median_distp. 

# filter the farmers_alb data for season 1, and then find the 20 closest season
# 1 farmers to median_distp. 

# To do that, create the new object closest_20farmers by using mutate with
# st_distance to create a new variable dist (convert it to numeric), and then 
# arrange by variable dist and slice out the top 20 observations. 

# Plot districts_alb in grey, median_dist over that in khaki, median_distp as a
# solid purple circle, farmers_alb in blue, and closest_20farmers in red. 

# Zero margins and width of 6 inches and height of 4 inches.

median_distp <- st_centroid(median_dist)
median_distp

farmers_alb1 <- farmers_alb %>% filter(season == 1)
farmers_alb1

# used chatgpt on this part in assembling the pipeline
closest_20farmers <- farmers_alb1 %>%
  mutate(dist = st_distance(geometry, median_distp)) %>%
  arrange(dist) %>%
  slice_head(n = 20)
closest_20farmers

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(median_dist %>% st_geometry(), col = "khaki", add = TRUE)
plot(median_distp, col = "purple", pch = 16, cex = 2, add = TRUE)
plot(farmers_alb1 %>% st_geometry(), col = "blue", add = TRUE)
plot(closest_20farmers %>% st_geometry(), col = "red", add = TRUE)
```

```{r, fig.width=6, fig.height=4, fig.align='center'}
# Create a rectangular sf polygon called mypol using the x coordinates 30 and 
# 31 (minimum and maximum) and y coordinates -10 and -11. 

# Assign it crs = 4326 and transform it to Albers. 

# Select from districts_alb the districts that intersect mypol, and plot in 
# “grey40” over districts_alb in grey, and plot over that mypol without any 
# fill but just a yellow border. 

# Calculate the area in ha of mypol and report it in your vignette below this 
# plot. 

# Zero margins and width of 6 inches and height of 4 inches.
mypol <- st_polygon(list(cbind(x = c(30, 31, 31, 30, 30), 
                             y = c(-10, -10, -11, -11, -10))))
mypol <- st_sfc(mypol)
mypol <- st_set_crs(mypol, "EPSG:4326")
mypol <- mypol %>% 
  st_transform(crs = st_crs(roads))
mypol

districts_alb_mypol <- districts_alb %>% 
  slice(st_intersects(x = mypol, y = districts_alb)[[1]])
districts_alb_mypol

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(districts_alb_mypol %>% st_geometry(), col = "grey40", add = TRUE)
plot(mypol %>% st_geometry(), col = NA, border = "yellow", add = TRUE)

mypol_area <- mypol %>% st_area() %>% units::set_units("ha")
mypol_area
```
I used chatGpt to format this so it was not in scientific notation.

### The area of mypol is `r format(mypol_area, scientific = FALSE)` hectares.


```{r, fig.width=6, fig.height=4, fig.align='center'}
#Create mypol_dist_int from the intersection of mypol and districts_alb, 
# recasting the intersected districts to multipolygons, and adding an area 
# variable onto it that reports areas of intersections in hectares. 

# Do all that in one pipeline. 

# Plot mypol_dist_int in rainbow colors over districts_alb. 

# Zero margins and width of 6 inches and height of 4 inches. 

# Report the mean and median of interections in the vignette below the plot.
mypol_dist_int <- districts_alb %>% 
  st_intersection(x = mypol, y = districts_alb) %>% 
  st_sf() %>% 
  st_cast("MULTIPOLYGON") %>% 
  mutate(area = as.numeric(units::set_units(st_area(.), "ha")))
mypol_dist_int

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(st_geometry(mypol_dist_int), col = rainbow(n = nrow(mypol_dist_int)), 
     add = TRUE)

mypol_median <- median(mypol_dist_int$area)
mypol_median

mypol_mean <- mean(mypol_dist_int$area)
mypol_mean
```
### The median of mypol is `r mypol_median`.
### The meam of mypol is `r mypol_mean`.

```{r, fig.width=6, fig.height=4, fig.align='center'}
# Find the shortest and longest roads in Zambia, and place the selected roads 
# into a new object (roads_extreme). 

# To do this, you will need to arrange roads by length and then slice to get 
# the first and last observations (of course you need to first calculate 
# length). 

# Do that as one pipeline. 

# Then calculate a 50 km buffer around those two roads (roads_extreme_buff). 

# Plot roads_extreme_buff in blue over districts_alb in grey, and add 
#roads_extreme on top of that as red lines (use lwd = 3 in the plot). 

# Zero margins and width of 6 inches and height of 4 inches.

roads_extreme <- roads %>% 
  mutate(length = as.numeric(units::set_units(st_length(.), "km"))) %>% 
  arrange(length) %>% 
  slice(c(1, 473))
roads_extreme

roads_extreme_buff <- roads_extreme %>% 
  st_buffer(dist = 50000)

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(roads_extreme_buff %>% st_geometry(), col = "blue", add = TRUE)
plot(roads_extreme %>% st_geometry(), col = 'red', lwd = 3, add = TRUE)
```

```{r, fig.width=6, fig.height=4, fig.align='center'}
# Select a random sample of 10 points in the smallest object in 
# roads_extreme_buff, and one of 50 in the largest object. 

# Use a single call to st_sample to do that. 

# Use a seed of 2. 

# Plot those points as yellow solid points over the same map created in 
# Task 8 above. 

# Use the same dimensions.

set.seed(2)
roads_extreme_buff_sample <- roads_extreme_buff %>% 
  st_sample(c(roads_extreme_buff$length), size = c(10, 50))

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(roads_extreme_buff %>% st_geometry(), col = "blue", add = TRUE)
plot(roads_extreme %>% st_geometry(), col = 'red', lwd = 3, add = TRUE)
plot(roads_extreme_buff_sample %>% 
       st_geometry(), col = 'yellow', pch = 16, add = TRUE)
```


```{r, fig.width=6, fig.height=4, fig.align='center'}
# Your final task is to intersect roads with the buffer of the longest road in
# roads_extreme_buff (roads_int). 

# Plot the buffer of the longest road in blue over the districts in grey, and 
# then roads_int as red lines. 

# Use the same dimensions as the previous two plots. 

# Report the total distance of intersected roads in km in the vignette below 
# the plot.

roads_int <- st_intersection(roads, roads_extreme_buff[2, ])
roads_int

par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey")
plot(roads_extreme_buff %>% st_geometry(), col = "blue", add = TRUE)
plot(roads_int %>% st_geometry(), col = 'red', lwd = 3, add = TRUE)

distance_km <- sum(st_length(roads_int)) %>% 
  units::set_units(., "km")
distance_km
```
### The total distance is of roads intersected in the buffer is `r distance_km`.
